name: flutter_cupertino_settings
description: Flutter widget to create an iOS settings-table (static TableView).
version: 0.7.0

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.44.0 <4.0.0"

dependencies:
  cupertino_icons: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.14.0