name: flutter_cupertino_settings
description: Flutter widget to create an iOS settings-table (static TableView).
version: 0.3.0
authors:
  - Matthias Rupp <matthias.rupp@posteo.de>
  - Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/matthinc/flutter_cupertino_settings

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

