name: flutter_cupertino_settings
description: Flutter widget to create an iOS settings-table (static TableView).
version: 0.5.0-nullsafety.0
authors:
  - Matthias Rupp <matthias.rupp@posteo.de>
  - Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/matthinc/flutter_cupertino_settings

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.23.0-0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  effective_dart: ^1.3.0
  lint: ^1.5.0